"""add new column2

Revision ID: 1137f8a95ddb
Revises: 837bc1aa4710
Create Date: 2024-04-07 08:46:51.545655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1137f8a95ddb'
down_revision = '837bc1aa4710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voucher', sa.Column('voucher_used_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voucher', 'voucher_used_timestamp')
    # ### end Alembic commands ###
