"""changes in fk in db

Revision ID: 2b992aea169e
Revises: 
Create Date: 2024-04-07 06:40:56.792639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b992aea169e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_string', sa.String(length=255), nullable=True),
    sa.Column('amount_of_processing_records_to_add', sa.Integer(), nullable=True),
    sa.Column('voucher_is_active', sa.Boolean(), nullable=True),
    sa.Column('voucher_created_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('amount_of_processing_records_to_add', sa.Integer(), nullable=True),
    sa.Column('transaction_amount', sa.Float(), nullable=True),
    sa.Column('transaction_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_history')
    op.drop_table('voucher')
    # ### end Alembic commands ###
