"""add new column

Revision ID: 837bc1aa4710
Revises: 2b992aea169e
Create Date: 2024-04-07 08:42:22.535146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837bc1aa4710'
down_revision = '2b992aea169e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voucher', sa.Column('voucher_used_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'voucher', 'user', ['voucher_used_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voucher', type_='foreignkey')
    op.drop_column('voucher', 'voucher_used_by_user_id')
    # ### end Alembic commands ###
